name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v3

      - name: Configuração .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.101'

      - name: Build
        run: dotnet build TechChallenge.API -c Release --verbosity minimal

      - name: Tests
        run: dotnet test TechChallenge.Tests -c Release --verbosity minimal --no-build --no-restore
