name: CI Workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v3

      - name: Configuração .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.0.101'

      - name: ls
        run: ls -l

      - name: Build
        run: dotnet build TechChallenge.sln -c Release --verbosity minimal

      - name: Tests
        run: dotnet test ./TechChallenge.Tests/TechChallenge.Tests.csproj -c Release --verbosity minimal --no-build --no-restore
