name: CI Workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: windows-latest

    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v3

      - name: Configuração .NET
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.0.101'

      - name: Criação do container
        run: |
          docker pull mcr.microsoft.com/mssql/server
          docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=1q2w3e4r@#$" -p 1433:1433 -d mcr.microsoft.com/mssql/server

      - name: Build
        run: dotnet build ./TechChallenge/TechChallenge.sln -c Release --verbosity minimal

      - name: Testes uninários
        run: dotnet test ./TechChallenge/TechChallenge.Tests/TechChallenge.Tests.csproj -c Release --verbosity minimal --no-build --no-restore

      - name: Testes de integração
        run: dotnet test ./TechChallenge/TechChallenge.Integration.Tests/TechChallenge.Integration.Tests.csproj -c Release --verbosity minimal --no-build --no-restore
