name: Primeiro WorkFlow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Cheking out
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: 'rdotti'
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ls -l
        run: ls -l

      - name: Docker Build and Push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./TechChallenge/TechChallenge.API/Dockerfile
          tags: 'rdotti/fiap-techchallenge:latest'
          push: true
