name: Primeiro WorkFlow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-hosted
    steps:
      - name: Cheking out
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: 'rdotti'
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker Build and Push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .        
          tags: 'latest'
          push: true
